# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine

WORKDIR /app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json .
COPY src ./src
COPY static ./static

RUN npm install --ignore-scripts \
    && npm run build

# Run the MCP server
CMD ["node", "dist/index.js"]
